function [ParametersofFracture,FracturesPath,FracturesLength,basisPonFracture,GradnubasisPonFracture,GradsigmabasisPonFracture] = ...
    SetFractureBasisData0(coordinates,elements3,ParametersofFracture,quad_x)
% time : 2019.2.14 - 2019.2.18
% modified on 2019.6.26, the basis data on tip of fractures is no longer zero. 
% author : xuziyao
% quad_x is distributed in [0,1].
% Basis function is barcentric polynomials(volumn coordinates) on the triangular element.
ParametersofFracture(:,11) = 0; % the number of elements which is passed by the k-th fracture
EtoEmap = triangulation_neighbor_triangles ( elements3 ); 
NumberofFractures = size(ParametersofFracture,1);
% ParametersofFracture: x_c,y_c,length,theta,width,permeability,xa,ya,xb,yb,
% # of elements which are passed through by this fracture. 
ParametersofFracture(:,7) = ParametersofFracture(:,1) - 1/2*ParametersofFracture(:,3).*cos(ParametersofFracture(:,4));
ParametersofFracture(:,8) = ParametersofFracture(:,2) - 1/2*ParametersofFracture(:,3).*sin(ParametersofFracture(:,4));
ParametersofFracture(:,9) = ParametersofFracture(:,1) + 1/2*ParametersofFracture(:,3).*cos(ParametersofFracture(:,4));
ParametersofFracture(:,10) = ParametersofFracture(:,2) + 1/2*ParametersofFracture(:,3).*sin(ParametersofFracture(:,4));
StartEndElements = zeros(NumberofFractures,2);
for jj = 1 : size(elements3,2) % compute the start and end elements of each fracture's path
    isStartElement = inpolygon( ParametersofFracture(:,7),ParametersofFracture(:,8),...
        coordinates(elements3([2;3;1;2],jj),1),coordinates(elements3([2;3;1;2],jj),2) );
    isEndElement   = inpolygon( ParametersofFracture(:,9),ParametersofFracture(:,10),...
        coordinates(elements3([2;3;1;2],jj),1),coordinates(elements3([2;3;1;2],jj),2) );
    StartEndElements(isStartElement,1) = jj;
    StartEndElements(isEndElement,2) = jj;
end
for k = 1 : NumberofFractures % compute ParametersofFracture(:,11), the number of elements along each fracture's path
    CurrentElement = StartEndElements(k,1); 
    ParametersofFracture(k,11) = ParametersofFracture(k,11) + 1;
    pp = 0;
    while ( CurrentElement ~= StartEndElements(k,2) )
        [~, ~, ii_int] = polyxpoly(coordinates(elements3([2;3;1;2],CurrentElement),1),coordinates(elements3([2;3;1;2],CurrentElement),2)...
           ,ParametersofFracture(k,[7,9]),ParametersofFracture(k,[8,10])); edge_int = ii_int(:,1);
        qq = setdiff(edge_int,pp);
        NextElement = EtoEmap(qq,CurrentElement);
        pp = find(EtoEmap(:,NextElement) == CurrentElement) ; 
        CurrentElement = NextElement;
        ParametersofFracture(k,11) = ParametersofFracture(k,11) + 1;
    end
end
FracturesPath = zeros(sum(ParametersofFracture(:,11)),1);
FracturesLength = zeros(sum(ParametersofFracture(:,11)),1);
basisPonFracture = zeros( 3*length(FracturesPath) , length(quad_x) + 2 );
GradnubasisPonFracture = zeros( 3*length(FracturesPath) , length(quad_x) + 2 );
GradsigmabasisPonFracture = zeros( 3*length(FracturesPath) , length(quad_x) + 2 );
CurrentIndex = 0;
for k = 1 : NumberofFractures
% compute the basis data for each element which is passed through by the
% k-th fracture:
    CurrentElement = StartEndElements(k,1); CurrentIndex = CurrentIndex + 1;
    FracturesPath(CurrentIndex) = CurrentElement;
    pp = 0; pplamda = [1,1,1;coordinates(elements3(:,CurrentElement),:)'] \ ...
              [1;ParametersofFracture(k,7);ParametersofFracture(k,8)];
    while ( CurrentElement ~= StartEndElements(k,2) )
        [x_int, y_int, ii_int] = polyxpoly(coordinates(elements3([2;3;1;2],CurrentElement),1),coordinates(elements3([2;3;1;2],CurrentElement),2)...
           ,ParametersofFracture(k,[7,9]),ParametersofFracture(k,[8,10])); edge_int = ii_int(:,1);
        qq = setdiff(edge_int,pp); qqlamda = [1,1,1;coordinates(elements3(:,CurrentElement),:)'] \ ...
              [1;x_int(edge_int==qq);y_int(edge_int==qq)];
          if length(edge_int) == 1 
                FracturesLength(CurrentIndex) = ...
                    sqrt( (x_int-ParametersofFracture(k,7))^2 + (y_int-ParametersofFracture(k,8))^2 );
          elseif length(edge_int) == 2 
                FracturesLength(CurrentIndex) = sqrt( diff(x_int)^2 + diff(y_int)^2 );
          else
              error('intersection points is not one or two');
          end
        % compute basis data (basisPonFracture,GradnubasisPonFracture) in the following:
        quad_lamda1 = pplamda(1) + (qqlamda(1)-pplamda(1))*[quad_x;0;1] ; 
        quad_lamda2 = pplamda(2) + (qqlamda(2)-pplamda(2))*[quad_x;0;1] ; 
        basisPonFracture( (CurrentIndex-1)*3 + 1 , :) = quad_lamda1;
        basisPonFracture( (CurrentIndex-1)*3 + 2 , :) = quad_lamda2;
        basisPonFracture( (CurrentIndex-1)*3 + 3 , :) = 1-quad_lamda1-quad_lamda2;
        GradnubasisPonFracture( (CurrentIndex-1)*3 + 1 , :) = (...
                [ones(size(quad_lamda1)),zeros(size(quad_lamda1))] * ...
            ( [1,0,0;0,1,0]*([1,1,1;coordinates(elements3(:,CurrentElement),:)']\[0,0;1,0;0,1]) * ...
              [cos(ParametersofFracture(k,4));sin(ParametersofFracture(k,4))] ) )';   
        GradnubasisPonFracture( (CurrentIndex-1)*3 + 2 , :) = (...
                [zeros(size(quad_lamda1)),ones(size(quad_lamda1))] * ...
            ( [1,0,0;0,1,0]*([1,1,1;coordinates(elements3(:,CurrentElement),:)']\[0,0;1,0;0,1]) * ...
              [cos(ParametersofFracture(k,4));sin(ParametersofFracture(k,4))] ) )';   
        GradnubasisPonFracture( (CurrentIndex-1)*3 + 3 , :) = (...
                [-ones(size(quad_lamda1)),-ones(size(quad_lamda1))] * ...
            ( [1,0,0;0,1,0]*([1,1,1;coordinates(elements3(:,CurrentElement),:)']\[0,0;1,0;0,1]) * ...
              [cos(ParametersofFracture(k,4));sin(ParametersofFracture(k,4))] ) )';   
        GradsigmabasisPonFracture( (CurrentIndex-1)*3 + 1 , :) = (...
                [ones(size(quad_lamda1)),zeros(size(quad_lamda1))] * ...
            ( [1,0,0;0,1,0]*([1,1,1;coordinates(elements3(:,CurrentElement),:)']\[0,0;1,0;0,1]) * ...
              [cos(ParametersofFracture(k,4)+pi/2);sin(ParametersofFracture(k,4)+pi/2)] ) )';   
        GradsigmabasisPonFracture( (CurrentIndex-1)*3 + 2 , :) = (...
                [zeros(size(quad_lamda1)),ones(size(quad_lamda1))] * ...
            ( [1,0,0;0,1,0]*([1,1,1;coordinates(elements3(:,CurrentElement),:)']\[0,0;1,0;0,1]) * ...
              [cos(ParametersofFracture(k,4)+pi/2);sin(ParametersofFracture(k,4)+pi/2)] ) )';   
        GradsigmabasisPonFracture( (CurrentIndex-1)*3 + 3 , :) = (...
                [-ones(size(quad_lamda1)),-ones(size(quad_lamda1))] * ...
            ( [1,0,0;0,1,0]*([1,1,1;coordinates(elements3(:,CurrentElement),:)']\[0,0;1,0;0,1]) * ...
              [cos(ParametersofFracture(k,4)+pi/2);sin(ParametersofFracture(k,4)+pi/2)] ) )';   
        NextElement = EtoEmap(qq,CurrentElement);
        pp = find(EtoEmap(:,NextElement) == CurrentElement); pplamda = [1,1,1;coordinates(elements3(:,NextElement),:)'] \ ...
              [1;x_int(edge_int==qq);y_int(edge_int==qq)];
        CurrentElement = NextElement; CurrentIndex = CurrentIndex + 1;
        FracturesPath(CurrentIndex) = CurrentElement;
    end
    [x_int, y_int, ~] = polyxpoly(coordinates(elements3([2;3;1;2],CurrentElement),1),coordinates(elements3([2;3;1;2],CurrentElement),2)...
       ,ParametersofFracture(k,[7,9]),ParametersofFracture(k,[8,10])); 
    qqlamda = [1,1,1;coordinates(elements3(:,CurrentElement),:)'] \ ...
          [1;ParametersofFracture(k,9);ParametersofFracture(k,10)];
    FracturesLength(CurrentIndex) = ...
           sqrt( (x_int-ParametersofFracture(k,9))^2 + (y_int-ParametersofFracture(k,10))^2 );
        % compute basis data (basisPonFracture,GradnubasisPonFracture) in the following:
        quad_lamda1 = pplamda(1) + (qqlamda(1)-pplamda(1))*[quad_x;0;1] ; 
        quad_lamda2 = pplamda(2) + (qqlamda(2)-pplamda(2))*[quad_x;0;1] ; 
        basisPonFracture( (CurrentIndex-1)*3 + 1 , :) = quad_lamda1;
        basisPonFracture( (CurrentIndex-1)*3 + 2 , :) = quad_lamda2;
        basisPonFracture( (CurrentIndex-1)*3 + 3 , :) = 1-quad_lamda1-quad_lamda2;
        GradnubasisPonFracture( (CurrentIndex-1)*3 + 1 , :) = (...
                [ones(size(quad_lamda1)),zeros(size(quad_lamda1))] * ...
            ( [1,0,0;0,1,0]*([1,1,1;coordinates(elements3(:,CurrentElement),:)']\[0,0;1,0;0,1]) * ...
              [cos(ParametersofFracture(k,4));sin(ParametersofFracture(k,4))] ) )';   
        GradnubasisPonFracture( (CurrentIndex-1)*3 + 2 , :) = (...
                [zeros(size(quad_lamda1)),ones(size(quad_lamda1))] * ...
            ( [1,0,0;0,1,0]*([1,1,1;coordinates(elements3(:,CurrentElement),:)']\[0,0;1,0;0,1]) * ...
              [cos(ParametersofFracture(k,4));sin(ParametersofFracture(k,4))] ) )';   
        GradnubasisPonFracture( (CurrentIndex-1)*3 + 3 , :) = (...
                [-ones(size(quad_lamda1)),-ones(size(quad_lamda1))] * ...
            ( [1,0,0;0,1,0]*([1,1,1;coordinates(elements3(:,CurrentElement),:)']\[0,0;1,0;0,1]) * ...
              [cos(ParametersofFracture(k,4));sin(ParametersofFracture(k,4))] ) )';   
        GradsigmabasisPonFracture( (CurrentIndex-1)*3 + 1 , :) = (...
                [ones(size(quad_lamda1)),zeros(size(quad_lamda1))] * ...
            ( [1,0,0;0,1,0]*([1,1,1;coordinates(elements3(:,CurrentElement),:)']\[0,0;1,0;0,1]) * ...
              [cos(ParametersofFracture(k,4)+pi/2);sin(ParametersofFracture(k,4)+pi/2)] ) )';   
        GradsigmabasisPonFracture( (CurrentIndex-1)*3 + 2 , :) = (...
                [zeros(size(quad_lamda1)),ones(size(quad_lamda1))] * ...
            ( [1,0,0;0,1,0]*([1,1,1;coordinates(elements3(:,CurrentElement),:)']\[0,0;1,0;0,1]) * ...
              [cos(ParametersofFracture(k,4)+pi/2);sin(ParametersofFracture(k,4)+pi/2)] ) )';   
        GradsigmabasisPonFracture( (CurrentIndex-1)*3 + 3 , :) = (...
                [-ones(size(quad_lamda1)),-ones(size(quad_lamda1))] * ...
            ( [1,0,0;0,1,0]*([1,1,1;coordinates(elements3(:,CurrentElement),:)']\[0,0;1,0;0,1]) * ...
              [cos(ParametersofFracture(k,4)+pi/2);sin(ParametersofFracture(k,4)+pi/2)] ) )';   
%        basisPonFracture( (CurrentIndex-ParametersofFracture(k,11))*3+1 :...
%            (CurrentIndex-ParametersofFracture(k,11)+1)*3, end-1 ) = 0;
%        GradnubasisPonFracture( (CurrentIndex-ParametersofFracture(k,11))*3+1 :...
%            (CurrentIndex-ParametersofFracture(k,11)+1)*3, end-1 ) = 0;
%        GradsigmabasisPonFracture( (CurrentIndex-ParametersofFracture(k,11))*3+1 :...
%            (CurrentIndex-ParametersofFracture(k,11)+1)*3, end-1 ) = 0;
%        basisPonFracture((CurrentIndex-1)*3+1 : CurrentIndex*3, end) = 0;
%        GradnubasisPonFracture((CurrentIndex-1)*3+1 : CurrentIndex*3, end) = 0;
%        GradsigmabasisPonFracture((CurrentIndex-1)*3+1 : CurrentIndex*3, end) = 0;
end
end